### PR TITLE
Use pkg-config; fix Poll() for ZeroMQ version 3

### PR DESCRIPTION
**Pull request by pebbe**
Two commits:

Use pkg-config, instead of assuming where libs and headers are.

Change the timeout in Poll() from uint64 to time.Duration.
Make it work for both ZeroMQ versions 2 and 3. The unit for
timeout changed between these two versions from microsecond
to millisecond.

### CODE REVIEW

**Comment by pebbe** [comment]
So, I'm new to this. I made some changes, did a pull request. Then I made more changes, and these end up in the same pull request.

Two additional changes:

I made an error in the code for Poll(). This is fixed in the fourth commit.

I merged the source files for different versions of ZeroMQ into one. I had to drop some variables, because these are not common to all versions. The reason for this was to make `go get` easier, no need to add tags. And I think it is best practice if the functionality is the same for all versions of ZeroMQ (up to a point). This is the third commit.

**Comment by alecthomas** [comment]
These are great changes, but I think they should be split into multiple pull requests.

To do that, create a branch with your changes and issue another pull request.

**Comment by ajanicij** [comment]
@pebbe That's a lot of changes! I looked at them quickly, but it is up to the owner of this project @alecthomas whether he will accept them or not. However, I have suggestions:
- the same as what @jtacoma told me: if you have more unrelated changes, it might be a good idea to send a smaller pull request and when it gets merged send another one and so on
- if you fix your own bug and make another commit, it is better to squash the two commits into one - such as commits 2 and 4 here

**Comment by alecthomas** [comment]
As a preliminary comment, maintaining backwards compatibility is fairly critical: not everybody is using zmq 3.x. With that in mind, removing constants isn't really an option.

One solution could be to maintain constants across versions, with zero values, but I think using tags are probably a better option.

**Comment by pebbe** [comment]
Undoing this mess. I will do separate pull request for separate issues.

**Pull request closed without merging**
