### PR TITLE
Socket option getters

### PR DESCRIPTION
**Pull request by jtacoma**
This is a response to @alecthomas' comment on #15, "I haven't merged this mainly because I haven't updated it for the new tagged version builds."  I'm not sure this code is ready for the master branch yet, but both `go test` (with libzmq-2.2.0) and `go test -tags zmq_3_x` (with libzmq-3.2.2) build and pass.

### CODE REVIEW

**Comment by jtacoma** [comment]
Oh wow... on second thought, looking at what GitHub is doing here, maybe I should have just linked to my branch from a comment on the original issue.

**Comment by jtacoma** [comment]
It's really just this one merge commit on the socket_options_getters branch: f2675ae6c6e590f087b7e262bb58c315847021d4

**Comment by alecthomas** [comment]
I'm not sure that link is right...it's "13 changed files with 1,127 additions and 264 deletions."...

I think the main problem now that the the build is split across tagged files is how you split an interface across them. I don't think it's possible? :\

**Comment by jtacoma** [comment]
Yeah, it's pretty messy as a pull request onto socket_option_getters.  Here's what it would look like if I'd requested it onto master instead:

https://github.com/alecthomas/gozmq/compare/master...jtacoma:socket_option_getters

Much cleaner.  You can see I dealt with the interface splitting issue by duplicating and specializing it in each of the zmq_[23]_x.go files.  I think a better approach would be to define all methods in one interface, and return errors from version-specific implementations that don't support particular options.  For backwards compatibility, it might be best to leave the general SetSockOpt\* methods on Socket itself.

I agree there's no nice way to do this, and I'm not gung-ho about getting this accepted: I just want to contribute something so I took a swing at the only open issue.  Now I really don't think this pull request is fitting and I have some new ideas about what to do instead...

**Comment by alecthomas** [comment]
Okay, thanks for having a play around. Looking forward to more pull requests! :)

**Pull request closed without merging**
