### PR TITLE
Tiny fix to make it installable

### PR DESCRIPTION
**Pull request by dahankzter**
Switching from String() to Error() in tests and added Error() method for zmqError.
All tests pass but no other checks made.

### CODE REVIEW

**Comment by AlekSi** [comment]
@alecthomas Any plans to pull this?

**Comment by alecthomas** [comment]
Merged, thanks dahankzter!

**Comment by dahankzter** [comment]
No problem!

Is it your intent to stay on weekly or go with release?

**Comment by alecthomas** [comment]
I'm going to track HEAD until 1.0 comes out, then I think I'll do the same thing gocode does:
- gozmq HEAD tracks Go HEAD
- Add tags for each Go release.

How does that sound?

**Comment by AlekSi** [comment]
gocode tracks weekly releases, not HEAD. Tags for releases (r60.3) are must-have, IMO.

**Comment by alecthomas** [comment]
Seems reasonable to me.

**Pull request closed without merging**
