### PR TITLE
Changed types Context and Socket from interface into struct.

### PR DESCRIPTION
**Pull request by pebbe**
This makes the methods visible in godoc. Using interfaces here is
not useful.
Also added checks for opening on a closed Socket or Context.

### CODE REVIEW

**Comment by jtacoma** [comment]
NewContext and NewSocket should return pointers to structs instead of structs, otherwise the structs will be copied by value and something like this wouldn't work:

```
a, _ := c.NewSocket(zmq.SUB)
b := a // b is a copy of a with closed==false
a.Close()
b.Close() // b still has closed==false, will try to re-close
```

About making methods visible in godoc, it sounds like "documentation-driven design".  I don't think I've seen that in other languages: it's something special about Go.

**Comment by alecthomas** [comment]
This has been discussed in the past, but the main issue is that it breaks backwards compatibility.

The methods in the interface can be documented, they just haven't been. Is that the main concern?

**Comment by pebbe** [comment]
The problem with the interface is that it is used to derive a type that is not exported. That means that all methods defined on that type are hidden for godoc.

What is the purpose for using an interface here?

**Comment by alecthomas** [comment]
There's no good reason, it's basically legacy.

**Comment by jtacoma** [comment]
I've been using some code generation to build socket option getters & setters, leading to nice godoc output: http://godoc.org/github.com/jtacoma/gozmqutil ...I could work out something similar for gozmq based on something like this if there's interest:

```
type Options struct { s *socket }
func (s *socket) Options() { return s.options }
// Generated code:
func (o *Options) GetLinger() (time.Duration, error) { ... }
```

...this gets us a non-interface type with the benefits of nice godoc output, and without breaking compatibility with code that expects Socket to be an interface.

Alternatively, sticking with this idea of replacing interfaces with pointers to structs, maybe we can find a way to provide something like `go tool fix` to update packages that depend on gozmq.

**Comment by alecthomas** [comment]
Something like `go tool fix` would be ideal I think.

**Pull request closed without merging**
