### PR TITLE
More options

### PR DESCRIPTION
**Pull request by jtacoma**
This adds some easily supported 3.x options: DelayAttachOnConnect, IPv4Only, MaxMsgSize, ROUTERMandatory, TCPAcceptFilter, and XPUBVerbose.  Some were already supported but didn't have their own friendly methods yet.  I made a separate commit for each option, for easier review.

Tested on my machine with Go 1.0.3 and libzmq 2.2.0 & 3.2.2.

Does anybody find the casing of these a bit awkward?  Maybe gozmqgen is difficult for others to modify and needs more inline documentation?

### CODE REVIEW

**Comment by jtacoma** [comment]
I just realized I didn't add support for resetting the TCP accept filter.  It's still possible through SetSockOptStringNil, but I want to add something like SetTCPAcceptFilterNil for completeness.  Please do not merge yet.

**Comment by alecthomas** [comment]
Otherwise, looks good.

**Comment by jtacoma** [comment]
Alright, as far as I know this is now ready to merge.

**Comment by alecthomas** [comment]
This no longer merges, but LGTM otherwise. Feel free to merge it in!

**Pull request merged**
